# Generated by Django 5.0.7 on 2024-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='balance_of_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('many', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='expense_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_days', models.IntegerField(max_length=2)),
                ('date', models.DateField()),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remainder', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alt_remainder', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saving', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='expenses_for_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('many', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='expenses_per_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('many', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
