# Generated by Django 5.0.7 on 2024-07-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_saving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_money', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='expense_table',
            name='balance_of_expenses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='budget_saving.balance_of_expenses'),
        ),
        migrations.AddField(
            model_name='expense_table',
            name='expenses_for_period',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense_table',
            name='expenses_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balance_of_expenses',
            name='many',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense_table',
            name='alt_remainder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense_table',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense_table',
            name='remainder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense_table',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense_table',
            name='saving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenses_for_period',
            name='many',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenses_per_day',
            name='many',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense_table',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_saving.dateperiod'),
        ),
    ]
