# Generated by Django 5.0.7 on 2024-07-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_saving', '0002_dateperiod_expense_table_balance_of_expenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense_table',
            old_name='date',
            new_name='dates',
        ),
    ]
